### ISSUE TITLE
Field 'browser' doesn't contain a valid alias configuration

### ISSUE THREAD

**Issue by dakshineshwar** [mohammed-io/frappe-gantt-react#1]
Please look at this issue. Its not working. Please suggest.
Error - [webpack] 'dist':
./node_modules/frappe-gantt-react/index.js
Module not found: Error: Can't resolve './dist/index' in 'D:\SharePointProject\SPProjectManagement\node_modules\f
rappe-gantt-react'
resolve './dist/index' in 'D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react'
  using description file: D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\package.json (
relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\package.
json (relative path: .)
    using description file: D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\package.json
 (relative path: ./dist/index)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\index doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\index.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\index.json doesn't exist
      as directory
        D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\index doesn't exist
[D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\index]
[D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\index.js]
[D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\index.json]
[D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\index]
 @ ./node_modules/frappe-gantt-react/index.js 3:17-40
 @ ./lib/webparts/taskManager/components/TaskManager.js
 @ ./lib/webparts/taskManager/TaskManagerWebPart.js
./node_modules/frappe-gantt-react/index.js
Module not found: Error: Can't resolve './dist/manifest' in 'D:\SharePointProject\SPProjectManagement\node_module
s\frappe-gantt-react'
resolve './dist/manifest' in 'D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react'
  using description file: D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\package.json (
relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\package.
json (relative path: .)
    using description file: D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\package.json
 (relative path: ./dist/manifest)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\manifest doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\manifest.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\manifest.json doesn't exist

      as directory
        D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\manifest doesn't exist
[D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\manifest]
[D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\manifest.js]
[D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\manifest.json]
[D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\manifest]
 @ ./node_modules/frappe-gantt-react/index.js 1:0-26
 @ ./lib/webparts/taskManager/components/TaskManager.js
 @ ./lib/webparts/taskManager/TaskManagerWebPart.js
./node_modules/frappe-gantt-react/index.js
Module not found: Error: Can't resolve './dist/vendor' in 'D:\SharePointProject\SPProjectManagement\node_modules\
frappe-gantt-react'
resolve './dist/vendor' in 'D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react'
  using description file: D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\package.json (
relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\package.
json (relative path: .)
    using description file: D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\package.json
 (relative path: ./dist/vendor)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\vendor doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\vendor.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\vendor.json doesn't exist
      as directory
        D:\SharePointProject\SPProjectManagement\node_modules\frappe-gantt-react\dist\vendor doesn't exist

**Comment by mohammed-io** [comment]
Hello, @dakshineshwar 
Sorry for delayed response,
thank you for your feedback,

The frappe team have updated their package, so it breaks the compatibility, I have to target the new version for this package.

My regards,

**Comment by dakshineshwar** [comment]
Hi @mohammed-io 
Once you target the new version for frappe-gantt please let me know.
