### ISSUE TITLE
@mohammed-io Module not found: Error: Can't resolve './dist/manifest'

### ISSUE THREAD

**Issue by dakshineshwar** [mohammed-io/frappe-gantt-react#2]
ERROR in ./~/frappe-gantt-react/index.js
Module not found: Error: Can't resolve './dist/manifest' in 'D:\React\simple-tsx-starter-kit\node_modules\frappe-
gantt-react'
 @ ./~/frappe-gantt-react/index.js 1:0-26
 @ ./src/app.tsx
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8888 webpack/hot/dev-server react-hot-loader/patch ./src/in
dex.tsx

ERROR in ./~/frappe-gantt-react/index.js
Module not found: Error: Can't resolve './dist/vendor' in 'D:\React\simple-tsx-starter-kit\node_modules\frappe-ga
ntt-react'
 @ ./~/frappe-gantt-react/index.js 2:0-24
 @ ./src/app.tsx
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8888 webpack/hot/dev-server react-hot-loader/patch ./src/in
dex.tsx

ERROR in ./~/frappe-gantt-react/index.js
Module not found: Error: Can't resolve './dist/index' in 'D:\React\simple-tsx-starter-kit\node_modules\frappe-gan
tt-react'
 @ ./~/frappe-gantt-react/index.js 3:17-40
 @ ./src/app.tsx
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8888 webpack/hot/dev-server react-hot-loader/patch ./src/in
dex.tsx

**Comment by minimuscle** [comment]
Did you find a solution to this?

**Comment by mohammed-io** [comment]
Hello @minimuscle 
Sorry for the delay, I was very busy most of the time.

I've re written the whole package again, please try it and let me know if you faced any issue :)

My regards
