### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by bratherem** [mohammed-io/frappe-gantt-react#3]
Failed to compile
./node_modules/frappe-gantt-react/index.js
Module not found: Can't resolve './dist/index' in '/Users/admin/PhpstormProjects/react-app/hackernews/node_modules/frappe-gantt-react'
This error occurred during the build time and cannot be dismissed.

**Comment by mohammed-io** [comment]
@bratherem 

The wrapper is re written from scratch

I apologize for the delay
